export const SET_INFO_PROMO = "SET_INFO_PROMO"
export const SET_REGISTRATION_USER = "SET_REGISTRATION_USER"
export const SET_AUTHENTICATED_USER = "SET_AUTHENTICATED_USER"

export const SET_WEEK_INFO_PROMO = "SET_WEEK_INFO_PROMO"

export const SET_RECOVERY_PASSWORD ="SET_RECOVERY_PASSWORD"